import React, { useState } from 'react'
import './products.css'
import Modal from '../../common/Modal'
import { Link } from 'react-router-dom'

const Products: React.FC = () => {
  const [open, setOpen] = useState<null | 'itinerary' | 'video' | 'ai'>(null)

  const trackClick = (placement: string) => {
    const id = (typeof crypto !== 'undefined' && (crypto as any).randomUUID)
      ? (crypto as any).randomUUID()
      : `${Date.now()}-${Math.random().toString(36).slice(2, 9)}`

    const payload = { placement, tp_click_id: id, ts: new Date().toISOString() }

    if (typeof navigator !== 'undefined' && 'sendBeacon' in navigator) {
      try {
        ;(navigator as any).sendBeacon('/api/clicks', JSON.stringify(payload))
      } catch (e) {
        void fetch('/api/clicks', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }).catch(() => {})
      }
    } else {
      void fetch('/api/clicks', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(payload) }).catch(() => {})
    }
  }

  return (
    <>
      <section id="products" className="products-section" aria-label="Products and pricing">
      <h2 className="products-title">Products</h2>

      <div className="products-grid">
        <div className="product-card">
          <h3>Itinerary Feed</h3>
          <p className="muted">Promoted cards inside itinerary and discovery feeds.</p>
          <p className="muted small">The Itinerary Feed surfaces items related to a traveler's plan — flights, hotels, activities, and nearby services — organized around destinations and trip dates. Ads here are shown as card-style recommendations that match the travel context (destination, dates, party size) so offers are highly relevant and actionable. For itinerary placements we can verify travel dates and surface time‑sensitive promotions (e.g., last-minute deals, local experiences).</p>
          <p className="muted small">Itineraries also include a social-matching feature so travelers can find companions: users can opt in to search for other travelers headed to the same destination with overlapping dates, connect securely, and coordinate plans. Privacy controls let users manage visibility and messaging preferences.</p>
          <ul>
            <li>Formats: image card, headline, price, CTA</li>
            <li>Targeting: destination, travel dates, trip intent</li>
            <li>Goals: bookings, leads, local visits</li>
          </ul>
          <div className="price"><button className="price-btn" onClick={() => setOpen('itinerary')}>CPC / CPM</button></div>
        </div>

        <div className="product-card">
          <h3>Video Feed</h3>
          <p className="muted">Short-form or in-stream video in the inspiration feed.</p>
          <p className="muted small">The Video Feed is built from authentic, user-uploaded travel videos — short clips of real experiences, destinations, and activities captured by travelers. This makes the feed a natural place for product video ads: ads can appear native alongside UGC, benefit from high engagement and watch time, and inspire viewers with real-world context. Video placements work especially well for showcasing experiences, demonstrations, or immersive storytelling that drives awareness and consideration.</p>
          <ul>
            <li>Formats: 6–30s vertical/landscape video</li>
            <li>Targeting: interest, contextual, demographic</li>
            <li>Goals: awareness, consideration, view-through conversions</li>
          </ul>
          <div className="price"><button className="price-btn" onClick={() => setOpen('video')}>CPV / CPM</button></div>
        </div>

        <div className="product-card">
          <h3>AI Itinerary Placement</h3>
          <p className="muted">Native recommendation inside AI-generated itineraries.</p>
          <p className="muted small">AI Itineraries are personalized, multi-day plans generated by our recommendation engine using traveler preferences and past behavior. Promoted placements in AI Itineraries are inserted as suggested activities or vendors that fit the generated plan — they must be labeled as 'Sponsored' and are ranked based on relevance and quality. These placements are valuable because they appear at the decision moment when travelers choose what to book or add to their itinerary.</p>
          <ul>
            <li>Formats: promoted native item with CTA and offer</li>
            <li>Targeting: contextual + itinerary signals</li>
            <li>Goals: high-intent conversions, sponsorships</li>
          </ul>
          <div className="price"><button className="price-btn" onClick={() => { trackClick('ai_itinerary'); setOpen('ai') }}>CPC / Premium CPM</button></div>
        </div>
      </div>

      <Modal open={open !== null} title="Pricing definitions" onClose={() => setOpen(null)}>
        {open === 'itinerary' && (
          <div>
            <p><strong>CPC</strong> — Cost Per Click: advertiser pays when a user clicks the ad.</p>
            <p><strong>CPM</strong> — Cost Per Mille: advertiser pays per 1,000 impressions; useful for awareness.</p>
          </div>
        )}
        {open === 'video' && (
          <div>
            <p><strong>CPV</strong> — Cost Per View: advertiser pays when a video view threshold is reached (e.g., 2s or 3s).</p>
            <p><strong>CPM</strong> — Cost Per Mille: advertiser pays per 1,000 impressions.</p>
          </div>
        )}
        {open === 'ai' && (
          <div>
            <p><strong>CPC</strong> — Cost Per Click: advertiser pays when a user clicks the promoted item.</p>
            <p><strong>CPM</strong> — Cost Per Mille: often used for sponsorship or prominence-based buys.</p>
          </div>
        )}
      </Modal>

      <h3 className="specs-title">Creative specs</h3>
      <div className="specs-grid">
        <div className="spec-card">
          <h4>Image Ad (Itinerary Card)</h4>
          <ul>
            <li>Recommended: 1200×675 (16:9) or 1080×1080 (1:1)</li>
            <li>Formats: PNG, JPG; max 2MB</li>
            <li>Text: headline ≤ 40 chars, description ≤ 90 chars</li>
            <li>Include: price or offer (optional), clear CTA</li>
          </ul>
        </div>

        <div className="spec-card">
          <h4>Video Ad (Feed)</h4>
          <ul>
            <li>Recommended: 1080×1920 (vertical) or 1280×720 (landscape)</li>
            <li>Durations: 6–30s (short), up to 60s supported</li>
            <li>Formats: MP4 (H.264), AAC audio; max 50MB</li>
            <li>Include: first 3s hook, explicit CTA in copy</li>
          </ul>
        </div>

        <div className="spec-card">
          <h4>Native AI Item</h4>
          <ul>
            <li>Recommended: image 1200×675; include title + short blurb</li>
            <li>Labeling: must be marked 'Sponsored' / 'Promoted'</li>
            <li>Formats: PNG, JPG, MP4 for rich placements</li>
          </ul>
        </div>
      </div>
      </section>
      <div style={{ padding: '0 2rem 2rem', maxWidth: 980, margin: '0 auto' }}>
        <p style={{ marginTop: '1rem' }}>See full pricing and example rates on the <Link to="/pricing">Pricing</Link> page.</p>
      </div>
    </>
  )
}

export default Products
